# Copyright (c) The ThingSet Project Contributors
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: thingset
      url-base: https://github.com/ThingSet
    - name: libresolar
      url-base: https://github.com/LibreSolar
  projects:
    - name: zephyr
      remote: libresolar
      revision: v3.4-branch
      import:
        name-allowlist:
          - cmsis
          - edtt
          - hal_espressif
          - hal_nordic
          - hal_stm32
          - hal_st
          - loramac-node
          - mbedtls
          - tinycrypt
          - picolibc
    - name: thingset-node-c
      remote: thingset
      revision: ef65aafb39c7df74da8c7b9b4079fb28bf4f19e3
      path: modules/thingset-node-c
      import: true
